version: '3.8'
services:
  pg_database:
    image: postgres
    container_name: 'template_pg'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
